[project]
authors = ["Misha Mikhasenko <mikhail.mikhasenko@gmail.com>"]
channels = ["conda-forge"]
description = "Educational materials for the K-matrix formalism in the field of hadron physics"
name = "international-k-matrix-day"
platforms = ["linux-64", "osx-64", "win-64"]
version = "0.1.0"

[dependencies]
ampform = "==0.15"
ipympl = ">=0.9.3,<0.10"
ipywidgets = ">=8.1.2,<8.2"
juliaup = ">=1.13.0"
jupyterlab = ">=4.1.5,<4.2"
jupyterlab-git = ">=0.50.0,<0.51"
jupyterlab-lsp = ">=5.1.0,<5.2"
jupyterlab-myst = ">=2.3.1,<2.4"
matplotlib = ">=3.8.3,<3.9"
nbstripout = ">=0.7.1,<0.8"
plotly = "==5.18"
python = "==3.10"
python-lsp-server = ">=1.10.1,<1.11"
sympy = "==1.12"

[tasks.build]
cmd = "julia --project -e 'using Pkg; Pkg.instantiate()'"
depends_on = [
    "install-julia",
]

[tasks.doc]
cmd = "julia --project=.. -e 'using PlutoSliderServer; PlutoSliderServer.export_directory(Export_output_dir=\"_build\")'"
cwd = "docs"
depends_on = [
    "build",
]

[tasks.install-julia]
cmd = """
    juliaup add 1.10.2 && \
    juliaup default 1.10.2
"""

[tasks.lab]
cmd = "jupyter lab docs"

[tasks.lint]
cmd = "nbstripout docs/*.ipynb"

[tasks.pluto]
cmd = "julia --project -e 'using Pluto; Pluto.run(notebook=\"docs/K-matrix.jl\")'"
depends_on = [
    "build",
]
