[project]
name = "international-k-matrix-day"
version = "0.1.0"
description = "Educational materials for the K-matrix formalism in the field of hadron physics"
authors = ["Misha Mikhasenko <mikhail.mikhasenko@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
juliaup = ">=1.13.0"
python = "==3.10"
jupyterlab-git = ">=0.50.0,<0.51"
ipywidgets = ">=8.1.2,<8.2"
python-lsp-server = ">=1.10.1,<1.11"
sympy = "==1.12"
nbstripout = ">=0.7.1,<0.8"
ampform = "==0.15"
jupyterlab-myst = ">=2.3.1,<2.4"
ipympl = ">=0.9.3,<0.10"
matplotlib = ">=3.8.3,<3.9"
plotly = "==5.18"
jupyterlab = ">=4.1.5,<4.2"
jupyterlab-lsp = ">=5.1.0,<5.2"

[tasks]
build = { cmd = "julia --project -e 'using Pkg; Pkg.instantiate()'", depends_on = [
    "install-julia",
] }
doc = { cmd = "julia --project=.. -e 'using PlutoSliderServer; PlutoSliderServer.export_directory(Export_output_dir=\"_build\")'", cwd ="docs", depends_on = [
    "build",
] }
install-julia = "juliaup add 1.10.2 && juliaup default 1.10.2"
pluto = { cmd = "julia --project -e 'using Pluto; Pluto.run(notebook=\"docs/K-matrix.jl\")'", depends_on = [
    "build",
] }
lab = "jupyter lab docs"
lint = "nbstripout docs/*.ipynb"
